DROP TABLE IF EXISTS anal_batter_rate;

CREATE TABLE anal_batter_rate AS

SELECT 

anal_game_date,
batter,
pname,

##### std ######

@outsmade_pa := outsmade_std/pa_std as outsmade_pa_std,
@hits_pa := hits_std/pa_std as hits_pa_std,
@avg_ := hits_std/(pa_std - walks_std - hbp_std - sacs_std) as avg_std,
@obp := onbases_std/pa_std as obp_std,
@sba_pa := selfbasesadv_std/pa_std as sba_pa_std,
@sba_o := selfbasesadv_std/outsmade_std as sba_o_std,
@rba_pa := runnerbasesadv_std/pa_std as rba_pa_std,
@rba_o := runnerbasesadv_std/outsmade_std as rba_o_std,
@tba_pa := totbasesadv_std/pa_std as tba_pa_std,
@tba_o := totbasesadv_std/outsmade_std as tba_o_std,
@k_pa := k_std/pa_std as k_pa_std,
@klook_pa := klook_std/pa_std as klook_pa_std,
@kswing_pa := kswing_std/pa_std as kswing_pa_std,
@walk_pa := walks_std/pa_std as walk_pa_std,
@singles_pa := singles_std/pa_std as singles_pa_std,
@doubles_pa := doubles_std/pa_std as doubles_pa_std,
@triples_pa := triples_std/pa_std as triples_pa_std,
@homeruns_pa := homeruns_std/pa_std as homeruns_pa_std,
@sacs_pa := sacs_std/pa_std as sacs_pa_std,
@groundballs_pa := groundballs_std/pa_std as groundballs_pa_std,
@linedrives_pa := linedrives_std/pa_std as linedrives_pa_std,

##### last60 ######

@outsmade_pa := outsmade_last60/pa_last60 as outsmade_pa_last60,
@hits_pa := hits_last60/pa_last60 as hits_pa_last60,
@avg_ := hits_last60/(pa_last60 - walks_last60 - hbp_last60 - sacs_last60) as avg_last60,
@obp := onbases_last60/pa_last60 as obp_last60,
@sba_pa := selfbasesadv_last60/pa_last60 as sba_pa_last60,
@sba_o := selfbasesadv_last60/outsmade_last60 as sba_o_last60,
@rba_pa := runnerbasesadv_last60/pa_last60 as rba_pa_last60,
@rba_o := runnerbasesadv_last60/outsmade_last60 as rba_o_last60,
@tba_pa := totbasesadv_last60/pa_last60 as tba_pa_last60,
@tba_o := totbasesadv_last60/outsmade_last60 as tba_o_last60,
@k_pa := k_last60/pa_last60 as k_pa_last60,
@klook_pa := klook_last60/pa_last60 as klook_pa_last60,
@kswing_pa := kswing_last60/pa_last60 as kswing_pa_last60,
@walk_pa := walks_last60/pa_last60 as walk_pa_last60,
@singles_pa := singles_last60/pa_last60 as singles_pa_last60,
@doubles_pa := doubles_last60/pa_last60 as doubles_pa_last60,
@triples_pa := triples_last60/pa_last60 as triples_pa_last60,
@homeruns_pa := homeruns_last60/pa_last60 as homeruns_pa_last60,
@sacs_pa := sacs_last60/pa_last60 as sacs_pa_last60,
@groundballs_pa := groundballs_last60/pa_last60 as groundballs_pa_last60,
@linedrives_pa := linedrives_last60/pa_last60 as linedrives_pa_last60,

##### last30 ######

@outsmade_pa := outsmade_last30/pa_last30 as outsmade_pa_last30,
@hits_pa := hits_last30/pa_last30 as hits_pa_last30,
@avg_ := hits_last30/(pa_last30 - walks_last30 - hbp_last30 - sacs_last30) as avg_last30,
@obp := onbases_last30/pa_last30 as obp_last30,
@sba_pa := selfbasesadv_last30/pa_last30 as sba_pa_last30,
@sba_o := selfbasesadv_last30/outsmade_last30 as sba_o_last30,
@rba_pa := runnerbasesadv_last30/pa_last30 as rba_pa_last30,
@rba_o := runnerbasesadv_last30/outsmade_last30 as rba_o_last30,
@tba_pa := totbasesadv_last30/pa_last30 as tba_pa_last30,
@tba_o := totbasesadv_last30/outsmade_last30 as tba_o_last30,
@k_pa := k_last30/pa_last30 as k_pa_last30,
@klook_pa := klook_last30/pa_last30 as klook_pa_last30,
@kswing_pa := kswing_last30/pa_last30 as kswing_pa_last30,
@walk_pa := walks_last30/pa_last30 as walk_pa_last30,
@singles_pa := singles_last30/pa_last30 as singles_pa_last30,
@doubles_pa := doubles_last30/pa_last30 as doubles_pa_last30,
@triples_pa := triples_last30/pa_last30 as triples_pa_last30,
@homeruns_pa := homeruns_last30/pa_last30 as homeruns_pa_last30,
@sacs_pa := sacs_last30/pa_last30 as sacs_pa_last30,
@groundballs_pa := groundballs_last30/pa_last30 as groundballs_pa_last30,
@linedrives_pa := linedrives_last30/pa_last30 as linedrives_pa_last30,

##### last10 ######

@outsmade_pa := outsmade_last10/pa_last10 as outsmade_pa_last10,
@hits_pa := hits_last10/pa_last10 as hits_pa_last10,
@avg_ := hits_last10/(pa_last10 - walks_last10 - hbp_last10 - sacs_last10) as avg_last10,
@obp := onbases_last10/pa_last10 as obp_last10,
@sba_pa := selfbasesadv_last10/pa_last10 as sba_pa_last10,
@sba_o := selfbasesadv_last10/outsmade_last10 as sba_o_last10,
@rba_pa := runnerbasesadv_last10/pa_last10 as rba_pa_last10,
@rba_o := runnerbasesadv_last10/outsmade_last10 as rba_o_last10,
@tba_pa := totbasesadv_last10/pa_last10 as tba_pa_last10,
@tba_o := totbasesadv_last10/outsmade_last10 as tba_o_last10,
@k_pa := k_last10/pa_last10 as k_pa_last10,
@klook_pa := klook_last10/pa_last10 as klook_pa_last10,
@kswing_pa := kswing_last10/pa_last10 as kswing_pa_last10,
@walk_pa := walks_last10/pa_last10 as walk_pa_last10,
@singles_pa := singles_last10/pa_last10 as singles_pa_last10,
@doubles_pa := doubles_last10/pa_last10 as doubles_pa_last10,
@triples_pa := triples_last10/pa_last10 as triples_pa_last10,
@homeruns_pa := homeruns_last10/pa_last10 as homeruns_pa_last10,
@sacs_pa := sacs_last10/pa_last10 as sacs_pa_last10,
@groundballs_pa := groundballs_last10/pa_last10 as groundballs_pa_last10,
@linedrives_pa := linedrives_last10/pa_last10 as linedrives_pa_last10,

##### std2 ######

@outsmade_pa := outsmade_std2/pa_std2 as outsmade_pa_std2,
@hits_pa := hits_std2/pa_std2 as hits_pa_std2,
@avg_ := hits_std2/(pa_std2 - walks_std2 - hbp_std2 - sacs_std2) as avg_std2,
@obp := onbases_std2/pa_std2 as obp_std2,
@sba_pa := selfbasesadv_std2/pa_std2 as sba_pa_std2,
@sba_o := selfbasesadv_std2/outsmade_std2 as sba_o_std2,
@rba_pa := runnerbasesadv_std2/pa_std2 as rba_pa_std2,
@rba_o := runnerbasesadv_std2/outsmade_std2 as rba_o_std2,
@tba_pa := totbasesadv_std2/pa_std2 as tba_pa_std2,
@tba_o := totbasesadv_std2/outsmade_std2 as tba_o_std2,
@k_pa := k_std2/pa_std2 as k_pa_std2,
@klook_pa := klook_std2/pa_std2 as klook_pa_std2,
@kswing_pa := kswing_std2/pa_std2 as kswing_pa_std2,
@walk_pa := walks_std2/pa_std2 as walk_pa_std2,
@singles_pa := singles_std2/pa_std2 as singles_pa_std2,
@doubles_pa := doubles_std2/pa_std2 as doubles_pa_std2,
@triples_pa := triples_std2/pa_std2 as triples_pa_std2,
@homeruns_pa := homeruns_std2/pa_std2 as homeruns_pa_std2,
@sacs_pa := sacs_std2/pa_std2 as sacs_pa_std2,
@groundballs_pa := groundballs_std2/pa_std2 as groundballs_pa_std2,
@linedrives_pa := linedrives_std2/pa_std2 as linedrives_pa_std2,

##### std3 ######

@outsmade_pa := outsmade_std3/pa_std3 as outsmade_pa_std3,
@hits_pa := hits_std3/pa_std3 as hits_pa_std3,
@avg_ := hits_std3/(pa_std3 - walks_std3 - hbp_std3 - sacs_std3) as avg_std3,
@obp := onbases_std3/pa_std3 as obp_std3,
@sba_pa := selfbasesadv_std3/pa_std3 as sba_pa_std3,
@sba_o := selfbasesadv_std3/outsmade_std3 as sba_o_std3,
@rba_pa := runnerbasesadv_std3/pa_std3 as rba_pa_std3,
@rba_o := runnerbasesadv_std3/outsmade_std3 as rba_o_std3,
@tba_pa := totbasesadv_std3/pa_std3 as tba_pa_std3,
@tba_o := totbasesadv_std3/outsmade_std3 as tba_o_std3,
@k_pa := k_std3/pa_std3 as k_pa_std3,
@klook_pa := klook_std3/pa_std3 as klook_pa_std3,
@kswing_pa := kswing_std3/pa_std3 as kswing_pa_std3,
@walk_pa := walks_std3/pa_std3 as walk_pa_std3,
@singles_pa := singles_std3/pa_std3 as singles_pa_std3,
@doubles_pa := doubles_std3/pa_std3 as doubles_pa_std3,
@triples_pa := triples_std3/pa_std3 as triples_pa_std3,
@homeruns_pa := homeruns_std3/pa_std3 as homeruns_pa_std3,
@sacs_pa := sacs_std3/pa_std3 as sacs_pa_std3,
@groundballs_pa := groundballs_std3/pa_std3 as groundballs_pa_std3,
@linedrives_pa := linedrives_std3/pa_std3 as linedrives_pa_std3,

##### std_rh ######

@outsmade_pa := outsmade_std_rh/pa_std_rh as outsmade_pa_std_rh,
@hits_pa := hits_std_rh/pa_std_rh as hits_pa_std_rh,
@avg_ := hits_std_rh/(pa_std_rh - walks_std_rh - hbp_std_rh - sacs_std_rh) as avg_std_rh,
@obp := onbases_std_rh/pa_std_rh as obp_std_rh,
@sba_pa := selfbasesadv_std_rh/pa_std_rh as sba_pa_std_rh,
@sba_o := selfbasesadv_std_rh/outsmade_std_rh as sba_o_std_rh,
@rba_pa := runnerbasesadv_std_rh/pa_std_rh as rba_pa_std_rh,
@rba_o := runnerbasesadv_std_rh/outsmade_std_rh as rba_o_std_rh,
@tba_pa := totbasesadv_std_rh/pa_std_rh as tba_pa_std_rh,
@tba_o := totbasesadv_std_rh/outsmade_std_rh as tba_o_std_rh,
@k_pa := k_std_rh/pa_std_rh as k_pa_std_rh,
@klook_pa := klook_std_rh/pa_std_rh as klook_pa_std_rh,
@kswing_pa := kswing_std_rh/pa_std_rh as kswing_pa_std_rh,
@walk_pa := walks_std_rh/pa_std_rh as walk_pa_std_rh,
@singles_pa := singles_std_rh/pa_std_rh as singles_pa_std_rh,
@doubles_pa := doubles_std_rh/pa_std_rh as doubles_pa_std_rh,
@triples_pa := triples_std_rh/pa_std_rh as triples_pa_std_rh,
@homeruns_pa := homeruns_std_rh/pa_std_rh as homeruns_pa_std_rh,
@sacs_pa := sacs_std_rh/pa_std_rh as sacs_pa_std_rh,
@groundballs_pa := groundballs_std_rh/pa_std_rh as groundballs_pa_std_rh,
@linedrives_pa := linedrives_std_rh/pa_std_rh as linedrives_pa_std_rh,

##### last60_rh ######

@outsmade_pa := outsmade_last60_rh/pa_last60_rh as outsmade_pa_last60_rh,
@hits_pa := hits_last60_rh/pa_last60_rh as hits_pa_last60_rh,
@avg_ := hits_last60_rh/(pa_last60_rh - walks_last60_rh - hbp_last60_rh - sacs_last60_rh) as avg_last60_rh,
@obp := onbases_last60_rh/pa_last60_rh as obp_last60_rh,
@sba_pa := selfbasesadv_last60_rh/pa_last60_rh as sba_pa_last60_rh,
@sba_o := selfbasesadv_last60_rh/outsmade_last60_rh as sba_o_last60_rh,
@rba_pa := runnerbasesadv_last60_rh/pa_last60_rh as rba_pa_last60_rh,
@rba_o := runnerbasesadv_last60_rh/outsmade_last60_rh as rba_o_last60_rh,
@tba_pa := totbasesadv_last60_rh/pa_last60_rh as tba_pa_last60_rh,
@tba_o := totbasesadv_last60_rh/outsmade_last60_rh as tba_o_last60_rh,
@k_pa := k_last60_rh/pa_last60_rh as k_pa_last60_rh,
@klook_pa := klook_last60_rh/pa_last60_rh as klook_pa_last60_rh,
@kswing_pa := kswing_last60_rh/pa_last60_rh as kswing_pa_last60_rh,
@walk_pa := walks_last60_rh/pa_last60_rh as walk_pa_last60_rh,
@singles_pa := singles_last60_rh/pa_last60_rh as singles_pa_last60_rh,
@doubles_pa := doubles_last60_rh/pa_last60_rh as doubles_pa_last60_rh,
@triples_pa := triples_last60_rh/pa_last60_rh as triples_pa_last60_rh,
@homeruns_pa := homeruns_last60_rh/pa_last60_rh as homeruns_pa_last60_rh,
@sacs_pa := sacs_last60_rh/pa_last60_rh as sacs_pa_last60_rh,
@groundballs_pa := groundballs_last60_rh/pa_last60_rh as groundballs_pa_last60_rh,
@linedrives_pa := linedrives_last60_rh/pa_last60_rh as linedrives_pa_last60_rh,

##### last30_rh ######

@outsmade_pa := outsmade_last30_rh/pa_last30_rh as outsmade_pa_last30_rh,
@hits_pa := hits_last30_rh/pa_last30_rh as hits_pa_last30_rh,
@avg_ := hits_last30_rh/(pa_last30_rh - walks_last30_rh - hbp_last30_rh - sacs_last30_rh) as avg_last30_rh,
@obp := onbases_last30_rh/pa_last30_rh as obp_last30_rh,
@sba_pa := selfbasesadv_last30_rh/pa_last30_rh as sba_pa_last30_rh,
@sba_o := selfbasesadv_last30_rh/outsmade_last30_rh as sba_o_last30_rh,
@rba_pa := runnerbasesadv_last30_rh/pa_last30_rh as rba_pa_last30_rh,
@rba_o := runnerbasesadv_last30_rh/outsmade_last30_rh as rba_o_last30_rh,
@tba_pa := totbasesadv_last30_rh/pa_last30_rh as tba_pa_last30_rh,
@tba_o := totbasesadv_last30_rh/outsmade_last30_rh as tba_o_last30_rh,
@k_pa := k_last30_rh/pa_last30_rh as k_pa_last30_rh,
@klook_pa := klook_last30_rh/pa_last30_rh as klook_pa_last30_rh,
@kswing_pa := kswing_last30_rh/pa_last30_rh as kswing_pa_last30_rh,
@walk_pa := walks_last30_rh/pa_last30_rh as walk_pa_last30_rh,
@singles_pa := singles_last30_rh/pa_last30_rh as singles_pa_last30_rh,
@doubles_pa := doubles_last30_rh/pa_last30_rh as doubles_pa_last30_rh,
@triples_pa := triples_last30_rh/pa_last30_rh as triples_pa_last30_rh,
@homeruns_pa := homeruns_last30_rh/pa_last30_rh as homeruns_pa_last30_rh,
@sacs_pa := sacs_last30_rh/pa_last30_rh as sacs_pa_last30_rh,
@groundballs_pa := groundballs_last30_rh/pa_last30_rh as groundballs_pa_last30_rh,
@linedrives_pa := linedrives_last30_rh/pa_last30_rh as linedrives_pa_last30_rh,

##### last10_rh ######

@outsmade_pa := outsmade_last10_rh/pa_last10_rh as outsmade_pa_last10_rh,
@hits_pa := hits_last10_rh/pa_last10_rh as hits_pa_last10_rh,
@avg_ := hits_last10_rh/(pa_last10_rh - walks_last10_rh - hbp_last10_rh - sacs_last10_rh) as avg_last10_rh,
@obp := onbases_last10_rh/pa_last10_rh as obp_last10_rh,
@sba_pa := selfbasesadv_last10_rh/pa_last10_rh as sba_pa_last10_rh,
@sba_o := selfbasesadv_last10_rh/outsmade_last10_rh as sba_o_last10_rh,
@rba_pa := runnerbasesadv_last10_rh/pa_last10_rh as rba_pa_last10_rh,
@rba_o := runnerbasesadv_last10_rh/outsmade_last10_rh as rba_o_last10_rh,
@tba_pa := totbasesadv_last10_rh/pa_last10_rh as tba_pa_last10_rh,
@tba_o := totbasesadv_last10_rh/outsmade_last10_rh as tba_o_last10_rh,
@k_pa := k_last10_rh/pa_last10_rh as k_pa_last10_rh,
@klook_pa := klook_last10_rh/pa_last10_rh as klook_pa_last10_rh,
@kswing_pa := kswing_last10_rh/pa_last10_rh as kswing_pa_last10_rh,
@walk_pa := walks_last10_rh/pa_last10_rh as walk_pa_last10_rh,
@singles_pa := singles_last10_rh/pa_last10_rh as singles_pa_last10_rh,
@doubles_pa := doubles_last10_rh/pa_last10_rh as doubles_pa_last10_rh,
@triples_pa := triples_last10_rh/pa_last10_rh as triples_pa_last10_rh,
@homeruns_pa := homeruns_last10_rh/pa_last10_rh as homeruns_pa_last10_rh,
@sacs_pa := sacs_last10_rh/pa_last10_rh as sacs_pa_last10_rh,
@groundballs_pa := groundballs_last10_rh/pa_last10_rh as groundballs_pa_last10_rh,
@linedrives_pa := linedrives_last10_rh/pa_last10_rh as linedrives_pa_last10_rh,

##### std2_rh ######

@outsmade_pa := outsmade_std2_rh/pa_std2_rh as outsmade_pa_std2_rh,
@hits_pa := hits_std2_rh/pa_std2_rh as hits_pa_std2_rh,
@avg_ := hits_std2_rh/(pa_std2_rh - walks_std2_rh - hbp_std2_rh - sacs_std2_rh) as avg_std2_rh,
@obp := onbases_std2_rh/pa_std2_rh as obp_std2_rh,
@sba_pa := selfbasesadv_std2_rh/pa_std2_rh as sba_pa_std2_rh,
@sba_o := selfbasesadv_std2_rh/outsmade_std2_rh as sba_o_std2_rh,
@rba_pa := runnerbasesadv_std2_rh/pa_std2_rh as rba_pa_std2_rh,
@rba_o := runnerbasesadv_std2_rh/outsmade_std2_rh as rba_o_std2_rh,
@tba_pa := totbasesadv_std2_rh/pa_std2_rh as tba_pa_std2_rh,
@tba_o := totbasesadv_std2_rh/outsmade_std2_rh as tba_o_std2_rh,
@k_pa := k_std2_rh/pa_std2_rh as k_pa_std2_rh,
@klook_pa := klook_std2_rh/pa_std2_rh as klook_pa_std2_rh,
@kswing_pa := kswing_std2_rh/pa_std2_rh as kswing_pa_std2_rh,
@walk_pa := walks_std2_rh/pa_std2_rh as walk_pa_std2_rh,
@singles_pa := singles_std2_rh/pa_std2_rh as singles_pa_std2_rh,
@doubles_pa := doubles_std2_rh/pa_std2_rh as doubles_pa_std2_rh,
@triples_pa := triples_std2_rh/pa_std2_rh as triples_pa_std2_rh,
@homeruns_pa := homeruns_std2_rh/pa_std2_rh as homeruns_pa_std2_rh,
@sacs_pa := sacs_std2_rh/pa_std2_rh as sacs_pa_std2_rh,
@groundballs_pa := groundballs_std2_rh/pa_std2_rh as groundballs_pa_std2_rh,
@linedrives_pa := linedrives_std2_rh/pa_std2_rh as linedrives_pa_std2_rh,

##### std3_rh ######

@outsmade_pa := outsmade_std3_rh/pa_std3_rh as outsmade_pa_std3_rh,
@hits_pa := hits_std3_rh/pa_std3_rh as hits_pa_std3_rh,
@avg_ := hits_std3_rh/(pa_std3_rh - walks_std3_rh - hbp_std3_rh - sacs_std3_rh) as avg_std3_rh,
@obp := onbases_std3_rh/pa_std3_rh as obp_std3_rh,
@sba_pa := selfbasesadv_std3_rh/pa_std3_rh as sba_pa_std3_rh,
@sba_o := selfbasesadv_std3_rh/outsmade_std3_rh as sba_o_std3_rh,
@rba_pa := runnerbasesadv_std3_rh/pa_std3_rh as rba_pa_std3_rh,
@rba_o := runnerbasesadv_std3_rh/outsmade_std3_rh as rba_o_std3_rh,
@tba_pa := totbasesadv_std3_rh/pa_std3_rh as tba_pa_std3_rh,
@tba_o := totbasesadv_std3_rh/outsmade_std3_rh as tba_o_std3_rh,
@k_pa := k_std3_rh/pa_std3_rh as k_pa_std3_rh,
@klook_pa := klook_std3_rh/pa_std3_rh as klook_pa_std3_rh,
@kswing_pa := kswing_std3_rh/pa_std3_rh as kswing_pa_std3_rh,
@walk_pa := walks_std3_rh/pa_std3_rh as walk_pa_std3_rh,
@singles_pa := singles_std3_rh/pa_std3_rh as singles_pa_std3_rh,
@doubles_pa := doubles_std3_rh/pa_std3_rh as doubles_pa_std3_rh,
@triples_pa := triples_std3_rh/pa_std3_rh as triples_pa_std3_rh,
@homeruns_pa := homeruns_std3_rh/pa_std3_rh as homeruns_pa_std3_rh,
@sacs_pa := sacs_std3_rh/pa_std3_rh as sacs_pa_std3_rh,
@groundballs_pa := groundballs_std3_rh/pa_std3_rh as groundballs_pa_std3_rh,
@linedrives_pa := linedrives_std3_rh/pa_std3_rh as linedrives_pa_std3_rh,

##### std_lh ######

@outsmade_pa := outsmade_std_lh/pa_std_lh as outsmade_pa_std_lh,
@hits_pa := hits_std_lh/pa_std_lh as hits_pa_std_lh,
@avg_ := hits_std_lh/(pa_std_lh - walks_std_lh - hbp_std_lh - sacs_std_lh) as avg_std_lh,
@obp := onbases_std_lh/pa_std_lh as obp_std_lh,
@sba_pa := selfbasesadv_std_lh/pa_std_lh as sba_pa_std_lh,
@sba_o := selfbasesadv_std_lh/outsmade_std_lh as sba_o_std_lh,
@rba_pa := runnerbasesadv_std_lh/pa_std_lh as rba_pa_std_lh,
@rba_o := runnerbasesadv_std_lh/outsmade_std_lh as rba_o_std_lh,
@tba_pa := totbasesadv_std_lh/pa_std_lh as tba_pa_std_lh,
@tba_o := totbasesadv_std_lh/outsmade_std_lh as tba_o_std_lh,
@k_pa := k_std_lh/pa_std_lh as k_pa_std_lh,
@klook_pa := klook_std_lh/pa_std_lh as klook_pa_std_lh,
@kswing_pa := kswing_std_lh/pa_std_lh as kswing_pa_std_lh,
@walk_pa := walks_std_lh/pa_std_lh as walk_pa_std_lh,
@singles_pa := singles_std_lh/pa_std_lh as singles_pa_std_lh,
@doubles_pa := doubles_std_lh/pa_std_lh as doubles_pa_std_lh,
@triples_pa := triples_std_lh/pa_std_lh as triples_pa_std_lh,
@homeruns_pa := homeruns_std_lh/pa_std_lh as homeruns_pa_std_lh,
@sacs_pa := sacs_std_lh/pa_std_lh as sacs_pa_std_lh,
@groundballs_pa := groundballs_std_lh/pa_std_lh as groundballs_pa_std_lh,
@linedrives_pa := linedrives_std_lh/pa_std_lh as linedrives_pa_std_lh,

##### last60_lh ######

@outsmade_pa := outsmade_last60_lh/pa_last60_lh as outsmade_pa_last60_lh,
@hits_pa := hits_last60_lh/pa_last60_lh as hits_pa_last60_lh,
@avg_ := hits_last60_lh/(pa_last60_lh - walks_last60_lh - hbp_last60_lh - sacs_last60_lh) as avg_last60_lh,
@obp := onbases_last60_lh/pa_last60_lh as obp_last60_lh,
@sba_pa := selfbasesadv_last60_lh/pa_last60_lh as sba_pa_last60_lh,
@sba_o := selfbasesadv_last60_lh/outsmade_last60_lh as sba_o_last60_lh,
@rba_pa := runnerbasesadv_last60_lh/pa_last60_lh as rba_pa_last60_lh,
@rba_o := runnerbasesadv_last60_lh/outsmade_last60_lh as rba_o_last60_lh,
@tba_pa := totbasesadv_last60_lh/pa_last60_lh as tba_pa_last60_lh,
@tba_o := totbasesadv_last60_lh/outsmade_last60_lh as tba_o_last60_lh,
@k_pa := k_last60_lh/pa_last60_lh as k_pa_last60_lh,
@klook_pa := klook_last60_lh/pa_last60_lh as klook_pa_last60_lh,
@kswing_pa := kswing_last60_lh/pa_last60_lh as kswing_pa_last60_lh,
@walk_pa := walks_last60_lh/pa_last60_lh as walk_pa_last60_lh,
@singles_pa := singles_last60_lh/pa_last60_lh as singles_pa_last60_lh,
@doubles_pa := doubles_last60_lh/pa_last60_lh as doubles_pa_last60_lh,
@triples_pa := triples_last60_lh/pa_last60_lh as triples_pa_last60_lh,
@homeruns_pa := homeruns_last60_lh/pa_last60_lh as homeruns_pa_last60_lh,
@sacs_pa := sacs_last60_lh/pa_last60_lh as sacs_pa_last60_lh,
@groundballs_pa := groundballs_last60_lh/pa_last60_lh as groundballs_pa_last60_lh,
@linedrives_pa := linedrives_last60_lh/pa_last60_lh as linedrives_pa_last60_lh,

##### last30_lh ######

@outsmade_pa := outsmade_last30_lh/pa_last30_lh as outsmade_pa_last30_lh,
@hits_pa := hits_last30_lh/pa_last30_lh as hits_pa_last30_lh,
@avg_ := hits_last30_lh/(pa_last30_lh - walks_last30_lh - hbp_last30_lh - sacs_last30_lh) as avg_last30_lh,
@obp := onbases_last30_lh/pa_last30_lh as obp_last30_lh,
@sba_pa := selfbasesadv_last30_lh/pa_last30_lh as sba_pa_last30_lh,
@sba_o := selfbasesadv_last30_lh/outsmade_last30_lh as sba_o_last30_lh,
@rba_pa := runnerbasesadv_last30_lh/pa_last30_lh as rba_pa_last30_lh,
@rba_o := runnerbasesadv_last30_lh/outsmade_last30_lh as rba_o_last30_lh,
@tba_pa := totbasesadv_last30_lh/pa_last30_lh as tba_pa_last30_lh,
@tba_o := totbasesadv_last30_lh/outsmade_last30_lh as tba_o_last30_lh,
@k_pa := k_last30_lh/pa_last30_lh as k_pa_last30_lh,
@klook_pa := klook_last30_lh/pa_last30_lh as klook_pa_last30_lh,
@kswing_pa := kswing_last30_lh/pa_last30_lh as kswing_pa_last30_lh,
@walk_pa := walks_last30_lh/pa_last30_lh as walk_pa_last30_lh,
@singles_pa := singles_last30_lh/pa_last30_lh as singles_pa_last30_lh,
@doubles_pa := doubles_last30_lh/pa_last30_lh as doubles_pa_last30_lh,
@triples_pa := triples_last30_lh/pa_last30_lh as triples_pa_last30_lh,
@homeruns_pa := homeruns_last30_lh/pa_last30_lh as homeruns_pa_last30_lh,
@sacs_pa := sacs_last30_lh/pa_last30_lh as sacs_pa_last30_lh,
@groundballs_pa := groundballs_last30_lh/pa_last30_lh as groundballs_pa_last30_lh,
@linedrives_pa := linedrives_last30_lh/pa_last30_lh as linedrives_pa_last30_lh,

##### last10_lh ######

@outsmade_pa := outsmade_last10_lh/pa_last10_lh as outsmade_pa_last10_lh,
@hits_pa := hits_last10_lh/pa_last10_lh as hits_pa_last10_lh,
@avg_ := hits_last10_lh/(pa_last10_lh - walks_last10_lh - hbp_last10_lh - sacs_last10_lh) as avg_last10_lh,
@obp := onbases_last10_lh/pa_last10_lh as obp_last10_lh,
@sba_pa := selfbasesadv_last10_lh/pa_last10_lh as sba_pa_last10_lh,
@sba_o := selfbasesadv_last10_lh/outsmade_last10_lh as sba_o_last10_lh,
@rba_pa := runnerbasesadv_last10_lh/pa_last10_lh as rba_pa_last10_lh,
@rba_o := runnerbasesadv_last10_lh/outsmade_last10_lh as rba_o_last10_lh,
@tba_pa := totbasesadv_last10_lh/pa_last10_lh as tba_pa_last10_lh,
@tba_o := totbasesadv_last10_lh/outsmade_last10_lh as tba_o_last10_lh,
@k_pa := k_last10_lh/pa_last10_lh as k_pa_last10_lh,
@klook_pa := klook_last10_lh/pa_last10_lh as klook_pa_last10_lh,
@kswing_pa := kswing_last10_lh/pa_last10_lh as kswing_pa_last10_lh,
@walk_pa := walks_last10_lh/pa_last10_lh as walk_pa_last10_lh,
@singles_pa := singles_last10_lh/pa_last10_lh as singles_pa_last10_lh,
@doubles_pa := doubles_last10_lh/pa_last10_lh as doubles_pa_last10_lh,
@triples_pa := triples_last10_lh/pa_last10_lh as triples_pa_last10_lh,
@homeruns_pa := homeruns_last10_lh/pa_last10_lh as homeruns_pa_last10_lh,
@sacs_pa := sacs_last10_lh/pa_last10_lh as sacs_pa_last10_lh,
@groundballs_pa := groundballs_last10_lh/pa_last10_lh as groundballs_pa_last10_lh,
@linedrives_pa := linedrives_last10_lh/pa_last10_lh as linedrives_pa_last10_lh,

##### std2_lh ######

@outsmade_pa := outsmade_std2_lh/pa_std2_lh as outsmade_pa_std2_lh,
@hits_pa := hits_std2_lh/pa_std2_lh as hits_pa_std2_lh,
@avg_ := hits_std2_lh/(pa_std2_lh - walks_std2_lh - hbp_std2_lh - sacs_std2_lh) as avg_std2_lh,
@obp := onbases_std2_lh/pa_std2_lh as obp_std2_lh,
@sba_pa := selfbasesadv_std2_lh/pa_std2_lh as sba_pa_std2_lh,
@sba_o := selfbasesadv_std2_lh/outsmade_std2_lh as sba_o_std2_lh,
@rba_pa := runnerbasesadv_std2_lh/pa_std2_lh as rba_pa_std2_lh,
@rba_o := runnerbasesadv_std2_lh/outsmade_std2_lh as rba_o_std2_lh,
@tba_pa := totbasesadv_std2_lh/pa_std2_lh as tba_pa_std2_lh,
@tba_o := totbasesadv_std2_lh/outsmade_std2_lh as tba_o_std2_lh,
@k_pa := k_std2_lh/pa_std2_lh as k_pa_std2_lh,
@klook_pa := klook_std2_lh/pa_std2_lh as klook_pa_std2_lh,
@kswing_pa := kswing_std2_lh/pa_std2_lh as kswing_pa_std2_lh,
@walk_pa := walks_std2_lh/pa_std2_lh as walk_pa_std2_lh,
@singles_pa := singles_std2_lh/pa_std2_lh as singles_pa_std2_lh,
@doubles_pa := doubles_std2_lh/pa_std2_lh as doubles_pa_std2_lh,
@triples_pa := triples_std2_lh/pa_std2_lh as triples_pa_std2_lh,
@homeruns_pa := homeruns_std2_lh/pa_std2_lh as homeruns_pa_std2_lh,
@sacs_pa := sacs_std2_lh/pa_std2_lh as sacs_pa_std2_lh,
@groundballs_pa := groundballs_std2_lh/pa_std2_lh as groundballs_pa_std2_lh,
@linedrives_pa := linedrives_std2_lh/pa_std2_lh as linedrives_pa_std2_lh,

##### std3_lh ######

@outsmade_pa := outsmade_std3_lh/pa_std3_lh as outsmade_pa_std3_lh,
@hits_pa := hits_std3_lh/pa_std3_lh as hits_pa_std3_lh,
@avg_ := hits_std3_lh/(pa_std3_lh - walks_std3_lh - hbp_std3_lh - sacs_std3_lh) as avg_std3_lh,
@obp := onbases_std3_lh/pa_std3_lh as obp_std3_lh,
@sba_pa := selfbasesadv_std3_lh/pa_std3_lh as sba_pa_std3_lh,
@sba_o := selfbasesadv_std3_lh/outsmade_std3_lh as sba_o_std3_lh,
@rba_pa := runnerbasesadv_std3_lh/pa_std3_lh as rba_pa_std3_lh,
@rba_o := runnerbasesadv_std3_lh/outsmade_std3_lh as rba_o_std3_lh,
@tba_pa := totbasesadv_std3_lh/pa_std3_lh as tba_pa_std3_lh,
@tba_o := totbasesadv_std3_lh/outsmade_std3_lh as tba_o_std3_lh,
@k_pa := k_std3_lh/pa_std3_lh as k_pa_std3_lh,
@klook_pa := klook_std3_lh/pa_std3_lh as klook_pa_std3_lh,
@kswing_pa := kswing_std3_lh/pa_std3_lh as kswing_pa_std3_lh,
@walk_pa := walks_std3_lh/pa_std3_lh as walk_pa_std3_lh,
@singles_pa := singles_std3_lh/pa_std3_lh as singles_pa_std3_lh,
@doubles_pa := doubles_std3_lh/pa_std3_lh as doubles_pa_std3_lh,
@triples_pa := triples_std3_lh/pa_std3_lh as triples_pa_std3_lh,
@homeruns_pa := homeruns_std3_lh/pa_std3_lh as homeruns_pa_std3_lh,
@sacs_pa := sacs_std3_lh/pa_std3_lh as sacs_pa_std3_lh,
@groundballs_pa := groundballs_std3_lh/pa_std3_lh as groundballs_pa_std3_lh,
@linedrives_pa := linedrives_std3_lh/pa_std3_lh as linedrives_pa_std3_lh

FROM anal_batter_counting

ORDER BY anal_game_date DESC, tba_pa_std DESC
;


ALTER TABLE anal_batter_rate ADD UNIQUE KEY (anal_game_date,batter);
ALTER TABLE anal_batter_rate ADD INDEX (batter);

#ALTER TABLE anal_batter_rate ADD COLUMN createddate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
#ALTER TABLE anal_batter_rate ADD COLUMN lastmodifiedddate timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP;
#ALTER TABLE anal_batter_rate ADD COLUMN anal_pitcher_counting_def_PK int auto_increment primary key;
