#DROP TABLE IF EXISTS anal_pitcher_rate;

#CREATE TABLE anal_pitcher_rate AS

INSERT INTO anal_pitcher_rate

SELECT 

p.anal_game_date,
p.pitcher,
p.pname,

##### std ######

@outsmade_pa := outsmade_std/pa_std as outsmade_pa_std,
@hits_pa := hits_std/pa_std as hits_pa_std,
@avg_ := hits_std/(pa_std - walks_std - hbp_std ) as avg_std,
@obp := onbases_std/pa_std as obp_std,
@tba_pa := totbasesadv_std/pa_std as tba_pa_std,
@tba_o := totbasesadv_std/outsmade_std as tba_o_std,
@k_pa := k_std/pa_std as k_pa_std,
@klook_pa := klook_std/pa_std as klook_pa_std,
@kswing_pa := kswing_std/pa_std as kswing_pa_std,
@walk_pa := walks_std/pa_std as walk_pa_std,
@singles_pa := singles_std/pa_std as singles_pa_std,
@doubles_pa := doubles_std/pa_std as doubles_pa_std,
@triples_pa := triples_std/pa_std as triples_pa_std,
@homeruns_pa := homeruns_std/pa_std as homeruns_pa_std,
@groundballs_pa := groundballs_std/pa_std as groundballs_pa_std,
@linedrives_pa := linedrives_std/pa_std as linedrives_pa_std,

@ball_p := ball_std/p_std as ball_p_std,
@ball_pa := ball_std/pa_std as ball_pa_std,
@strike_p := strike_std/p_std as strike_p_std,
@strike_pa := strike_std/pa_std as strike_pa_std,

@calledstrike_strike := calledstrike_std/strike_std as calledstrike_strike_std,
@whiffstrike_strike := whiffstrike_std/strike_std as whiffstrike_strike_std,
@foulstrike_strike := foulstrike_std/strike_std as foulstrike_strike_std,
@inplay_strike := inplay_std/strike_std as inplay_strike_std,
@calledstrike_pa := calledstrike_std/pa_std as calledstrike_pa_std,
@whiffstrike_pa := whiffstrike_std/pa_std as whiffstrike_pa_std,
@foulstrike_pa := foulstrike_std/pa_std as foulstrike_pa_std,
@inplay_pa := inplay_std/pa_std as inplay_pa_std,

@swing_p := swing_std/p_std as swing_p_std,
@take_p := take_std/p_std as take_p_std,
@swing_pa := swing_std/pa_std as swing_pa_std,
@take_pa := take_std/pa_std as take_pa_std,

@firstpstrike_pa := firstpstrike_std/pa_std as firstpstrike_pa_std,
@secondpstrike_pa := secondpstrike_std/firstpnotinplay_fl_std as secondpstrike_pa_std,

@zoneedge_in2_p := zoneedge_in2_std/p_std as zoneedge_in2_p_std,
@zoneedge_in4_p := zoneedge_in4_std/p_std as zoneedge_in4_p_std,
@zoneedge_out2_p := zoneedge_out2_std/p_std as zoneedge_out2_p_std,
@zoneedge_out4_p := zoneedge_out4_std/p_std as zoneedge_out4_p_std,
@zonecorn_in2_p := zonecorn_in2_std/p_std as zonecorn_in2_p_std,
@zonecorn_in4_p := zonecorn_in4_std/p_std as zonecorn_in4_p_std,
@zonecorn_out2_p := zonecorn_out2_std/p_std as zonecorn_out2_p_std,
@zonecorn_out4_p := zonecorn_out4_std/p_std as zonecorn_out4_p_std,
@zone_mid3_p := zone_mid3_std/p_std as zone_mid3_p_std,
@zone_mid6_p := zone_mid6_std/p_std as zone_mid6_p_std,
@zone_bigmiss4_p := zone_bigmiss4_std/p_std as zone_bigmiss4_p_std,

@fastball_p := fastball_std/p_std as fastball_p_std,
@fastball_endspeed_p := fastball_endspeed_std/p_std as fastball_endspeed_p_std,
@fastball_spinrate_p := fastball_spinrate_std/p_std as fastball_spinrate_p_std,
@fastball_spindir_p := fastball_spindir_std/p_std as fastball_spindir_p_std,
@fastball_pfx_x_p := fastball_pfx_x_std/p_std as fastball_pfx_x_p_std,
@fastball_pfx_z_p := fastball_pfx_z_std/p_std as fastball_pfx_z_p_std,
@fastball_mnorm_p := fastball_mnorm_std/p_std as fastball_mnorm_p_std,
@fastball_adjmnorm_p := fastball_adjmnorm_std/p_std as fastball_adjmnorm_p_std,

@curveball_p := curveball_std/p_std as curveball_p_std,
@curveball_endspeed_p := curveball_endspeed_std/p_std as curveball_endspeed_p_std,
@curveball_spinrate_p := curveball_spinrate_std/p_std as curveball_spinrate_p_std,
@curveball_spindir_p := curveball_spindir_std/p_std as curveball_spindir_p_std,
@curveball_pfx_x_p := curveball_pfx_x_std/p_std as curveball_pfx_x_p_std,
@curveball_pfx_z_p := curveball_pfx_z_std/p_std as curveball_pfx_z_p_std,
@curveball_mnorm_p := curveball_mnorm_std/p_std as curveball_mnorm_p_std,
@curveball_adjmnorm_p := curveball_adjmnorm_std/p_std as curveball_adjmnorm_p_std,

@slider_p := slider_std/p_std as slider_p_std,
@slider_endspeed_p := slider_endspeed_std/p_std as slider_endspeed_p_std,
@slider_spinrate_p := slider_spinrate_std/p_std as slider_spinrate_p_std,
@slider_spindir_p := slider_spindir_std/p_std as slider_spindir_p_std,
@slider_pfx_x_p := slider_pfx_x_std/p_std as slider_pfx_x_p_std,
@slider_pfx_z_p := slider_pfx_z_std/p_std as slider_pfx_z_p_std,
@slider_mnorm_p := slider_mnorm_std/p_std as slider_mnorm_p_std,
@slider_adjmnorm_p := slider_adjmnorm_std/p_std as slider_adjmnorm_p_std,

@changeup_p := changeup_std/p_std as changeup_p_std,
@changeup_endspeed_p := changeup_endspeed_std/p_std as changeup_endspeed_p_std,
@changeup_spinrate_p := changeup_spinrate_std/p_std as changeup_spinrate_p_std,
@changeup_spindir_p := changeup_spindir_std/p_std as changeup_spindir_p_std,
@changeup_pfx_x_p := changeup_pfx_x_std/p_std as changeup_pfx_x_p_std,
@changeup_pfx_z_p := changeup_pfx_z_std/p_std as changeup_pfx_z_p_std,
@changeup_mnorm_p := changeup_mnorm_std/p_std as changeup_mnorm_p_std,
@changeup_adjmnorm_p := changeup_adjmnorm_std/p_std as changeup_adjmnorm_p_std,

##### std2 ######

@outsmade_pa := outsmade_std2/pa_std2 as outsmade_pa_std2,
@hits_pa := hits_std2/pa_std2 as hits_pa_std2,
@avg_ := hits_std2/(pa_std2 - walks_std2 - hbp_std2) as avg_std2,
@obp := onbases_std2/pa_std2 as obp_std2,
@tba_pa := totbasesadv_std2/pa_std2 as tba_pa_std2,
@tba_o := totbasesadv_std2/outsmade_std2 as tba_o_std2,
@k_pa := k_std2/pa_std2 as k_pa_std2,
@klook_pa := klook_std2/pa_std2 as klook_pa_std2,
@kswing_pa := kswing_std2/pa_std2 as kswing_pa_std2,
@walk_pa := walks_std2/pa_std2 as walk_pa_std2,
@singles_pa := singles_std2/pa_std2 as singles_pa_std2,
@doubles_pa := doubles_std2/pa_std2 as doubles_pa_std2,
@triples_pa := triples_std2/pa_std2 as triples_pa_std2,
@homeruns_pa := homeruns_std2/pa_std2 as homeruns_pa_std2,
@groundballs_pa := groundballs_std2/pa_std2 as groundballs_pa_std2,
@linedrives_pa := linedrives_std2/pa_std2 as linedrives_pa_std2,

@ball_p := ball_std2/p_std2 as ball_p_std2,
@ball_pa := ball_std2/pa_std2 as ball_pa_std2,
@strike_p := strike_std2/p_std2 as strike_p_std2,
@strike_pa := strike_std2/pa_std2 as strike_pa_std2,

@calledstrike_strike := calledstrike_std2/strike_std2 as calledstrike_strike_std2,
@whiffstrike_strike := whiffstrike_std2/strike_std2 as whiffstrike_strike_std2,
@foulstrike_strike := foulstrike_std2/strike_std2 as foulstrike_strike_std2,
@inplay_strike := inplay_std2/strike_std2 as inplay_strike_std2,
@calledstrike_pa := calledstrike_std2/pa_std2 as calledstrike_pa_std2,
@whiffstrike_pa := whiffstrike_std2/pa_std2 as whiffstrike_pa_std2,
@foulstrike_pa := foulstrike_std2/pa_std2 as foulstrike_pa_std2,
@inplay_pa := inplay_std2/pa_std2 as inplay_pa_std2,

@swing_p := swing_std2/p_std2 as swing_p_std2,
@take_p := take_std2/p_std2 as take_p_std2,
@swing_pa := swing_std2/pa_std2 as swing_pa_std2,
@take_pa := take_std2/pa_std2 as take_pa_std2,

@firstpstrike_pa := firstpstrike_std2/pa_std2 as firstpstrike_pa_std2,
@secondpstrike_pa := secondpstrike_std2/firstpnotinplay_fl_std2 as secondpstrike_pa_std2,

@zoneedge_in2_p := zoneedge_in2_std2/p_std2 as zoneedge_in2_p_std2,
@zoneedge_in4_p := zoneedge_in4_std2/p_std2 as zoneedge_in4_p_std2,
@zoneedge_out2_p := zoneedge_out2_std2/p_std2 as zoneedge_out2_p_std2,
@zoneedge_out4_p := zoneedge_out4_std2/p_std2 as zoneedge_out4_p_std2,
@zonecorn_in2_p := zonecorn_in2_std2/p_std2 as zonecorn_in2_p_std2,
@zonecorn_in4_p := zonecorn_in4_std2/p_std2 as zonecorn_in4_p_std2,
@zonecorn_out2_p := zonecorn_out2_std2/p_std2 as zonecorn_out2_p_std2,
@zonecorn_out4_p := zonecorn_out4_std2/p_std2 as zonecorn_out4_p_std2,
@zone_mid3_p := zone_mid3_std2/p_std2 as zone_mid3_p_std2,
@zone_mid6_p := zone_mid6_std2/p_std2 as zone_mid6_p_std2,
@zone_bigmiss4_p := zone_bigmiss4_std2/p_std2 as zone_bigmiss4_p_std2,

@fastball_p := fastball_std2/p_std2 as fastball_p_std2,
@fastball_endspeed_p := fastball_endspeed_std2/p_std2 as fastball_endspeed_p_std2,
@fastball_spinrate_p := fastball_spinrate_std2/p_std2 as fastball_spinrate_p_std2,
@fastball_spindir_p := fastball_spindir_std2/p_std2 as fastball_spindir_p_std2,
@fastball_pfx_x_p := fastball_pfx_x_std2/p_std2 as fastball_pfx_x_p_std2,
@fastball_pfx_z_p := fastball_pfx_z_std2/p_std2 as fastball_pfx_z_p_std2,
@fastball_mnorm_p := fastball_mnorm_std2/p_std2 as fastball_mnorm_p_std2,
@fastball_adjmnorm_p := fastball_adjmnorm_std2/p_std2 as fastball_adjmnorm_p_std2,

@curveball_p := curveball_std2/p_std2 as curveball_p_std2,
@curveball_endspeed_p := curveball_endspeed_std2/p_std2 as curveball_endspeed_p_std2,
@curveball_spinrate_p := curveball_spinrate_std2/p_std2 as curveball_spinrate_p_std2,
@curveball_spindir_p := curveball_spindir_std2/p_std2 as curveball_spindir_p_std2,
@curveball_pfx_x_p := curveball_pfx_x_std2/p_std2 as curveball_pfx_x_p_std2,
@curveball_pfx_z_p := curveball_pfx_z_std2/p_std2 as curveball_pfx_z_p_std2,
@curveball_mnorm_p := curveball_mnorm_std2/p_std2 as curveball_mnorm_p_std2,
@curveball_adjmnorm_p := curveball_adjmnorm_std2/p_std2 as curveball_adjmnorm_p_std2,

@slider_p := slider_std2/p_std2 as slider_p_std2,
@slider_endspeed_p := slider_endspeed_std2/p_std2 as slider_endspeed_p_std2,
@slider_spinrate_p := slider_spinrate_std2/p_std2 as slider_spinrate_p_std2,
@slider_spindir_p := slider_spindir_std2/p_std2 as slider_spindir_p_std2,
@slider_pfx_x_p := slider_pfx_x_std2/p_std2 as slider_pfx_x_p_std2,
@slider_pfx_z_p := slider_pfx_z_std2/p_std2 as slider_pfx_z_p_std2,
@slider_mnorm_p := slider_mnorm_std2/p_std2 as slider_mnorm_p_std2,
@slider_adjmnorm_p := slider_adjmnorm_std2/p_std2 as slider_adjmnorm_p_std2,

@changeup_p := changeup_std2/p_std2 as changeup_p_std2,
@changeup_endspeed_p := changeup_endspeed_std2/p_std2 as changeup_endspeed_p_std2,
@changeup_spinrate_p := changeup_spinrate_std2/p_std2 as changeup_spinrate_p_std2,
@changeup_spindir_p := changeup_spindir_std2/p_std2 as changeup_spindir_p_std2,
@changeup_pfx_x_p := changeup_pfx_x_std2/p_std2 as changeup_pfx_x_p_std2,
@changeup_pfx_z_p := changeup_pfx_z_std2/p_std2 as changeup_pfx_z_p_std2,
@changeup_mnorm_p := changeup_mnorm_std2/p_std2 as changeup_mnorm_p_std2,
@changeup_adjmnorm_p := changeup_adjmnorm_std2/p_std2 as changeup_adjmnorm_p_std2,

##### std3 ######

@outsmade_pa := outsmade_std3/pa_std3 as outsmade_pa_std3,
@hits_pa := hits_std3/pa_std3 as hits_pa_std3,
@avg_ := hits_std3/(pa_std3 - walks_std3 - hbp_std3) as avg_std3,
@obp := onbases_std3/pa_std3 as obp_std3,
@tba_pa := totbasesadv_std3/pa_std3 as tba_pa_std3,
@tba_o := totbasesadv_std3/outsmade_std3 as tba_o_std3,
@k_pa := k_std3/pa_std3 as k_pa_std3,
@klook_pa := klook_std3/pa_std3 as klook_pa_std3,
@kswing_pa := kswing_std3/pa_std3 as kswing_pa_std3,
@walk_pa := walks_std3/pa_std3 as walk_pa_std3,
@singles_pa := singles_std3/pa_std3 as singles_pa_std3,
@doubles_pa := doubles_std3/pa_std3 as doubles_pa_std3,
@triples_pa := triples_std3/pa_std3 as triples_pa_std3,
@homeruns_pa := homeruns_std3/pa_std3 as homeruns_pa_std3,
@groundballs_pa := groundballs_std3/pa_std3 as groundballs_pa_std3,
@linedrives_pa := linedrives_std3/pa_std3 as linedrives_pa_std3,

@ball_p := ball_std3/p_std3 as ball_p_std3,
@ball_pa := ball_std3/pa_std3 as ball_pa_std3,
@strike_p := strike_std3/p_std3 as strike_p_std3,
@strike_pa := strike_std3/pa_std3 as strike_pa_std3,

@calledstrike_strike := calledstrike_std3/strike_std3 as calledstrike_strike_std3,
@whiffstrike_strike := whiffstrike_std3/strike_std3 as whiffstrike_strike_std3,
@foulstrike_strike := foulstrike_std3/strike_std3 as foulstrike_strike_std3,
@inplay_strike := inplay_std3/strike_std3 as inplay_strike_std3,
@calledstrike_pa := calledstrike_std3/pa_std3 as calledstrike_pa_std3,
@whiffstrike_pa := whiffstrike_std3/pa_std3 as whiffstrike_pa_std3,
@foulstrike_pa := foulstrike_std3/pa_std3 as foulstrike_pa_std3,
@inplay_pa := inplay_std3/pa_std3 as inplay_pa_std3,

@swing_p := swing_std3/p_std3 as swing_p_std3,
@take_p := take_std3/p_std3 as take_p_std3,
@swing_pa := swing_std3/pa_std3 as swing_pa_std3,
@take_pa := take_std3/pa_std3 as take_pa_std3,

@firstpstrike_pa := firstpstrike_std3/pa_std3 as firstpstrike_pa_std3,
@secondpstrike_pa := secondpstrike_std3/firstpnotinplay_fl_std3 as secondpstrike_pa_std3,

@zoneedge_in2_p := zoneedge_in2_std3/p_std3 as zoneedge_in2_p_std3,
@zoneedge_in4_p := zoneedge_in4_std3/p_std3 as zoneedge_in4_p_std3,
@zoneedge_out2_p := zoneedge_out2_std3/p_std3 as zoneedge_out2_p_std3,
@zoneedge_out4_p := zoneedge_out4_std3/p_std3 as zoneedge_out4_p_std3,
@zonecorn_in2_p := zonecorn_in2_std3/p_std3 as zonecorn_in2_p_std3,
@zonecorn_in4_p := zonecorn_in4_std3/p_std3 as zonecorn_in4_p_std3,
@zonecorn_out2_p := zonecorn_out2_std3/p_std3 as zonecorn_out2_p_std3,
@zonecorn_out4_p := zonecorn_out4_std3/p_std3 as zonecorn_out4_p_std3,
@zone_mid3_p := zone_mid3_std3/p_std3 as zone_mid3_p_std3,
@zone_mid6_p := zone_mid6_std3/p_std3 as zone_mid6_p_std3,
@zone_bigmiss4_p := zone_bigmiss4_std3/p_std3 as zone_bigmiss4_p_std3,

@fastball_p := fastball_std3/p_std3 as fastball_p_std3,
@fastball_endspeed_p := fastball_endspeed_std3/p_std3 as fastball_endspeed_p_std3,
@fastball_spinrate_p := fastball_spinrate_std3/p_std3 as fastball_spinrate_p_std3,
@fastball_spindir_p := fastball_spindir_std3/p_std3 as fastball_spindir_p_std3,
@fastball_pfx_x_p := fastball_pfx_x_std3/p_std3 as fastball_pfx_x_p_std3,
@fastball_pfx_z_p := fastball_pfx_z_std3/p_std3 as fastball_pfx_z_p_std3,
@fastball_mnorm_p := fastball_mnorm_std3/p_std3 as fastball_mnorm_p_std3,
@fastball_adjmnorm_p := fastball_adjmnorm_std3/p_std3 as fastball_adjmnorm_p_std3,

@curveball_p := curveball_std3/p_std3 as curveball_p_std3,
@curveball_endspeed_p := curveball_endspeed_std3/p_std3 as curveball_endspeed_p_std3,
@curveball_spinrate_p := curveball_spinrate_std3/p_std3 as curveball_spinrate_p_std3,
@curveball_spindir_p := curveball_spindir_std3/p_std3 as curveball_spindir_p_std3,
@curveball_pfx_x_p := curveball_pfx_x_std3/p_std3 as curveball_pfx_x_p_std3,
@curveball_pfx_z_p := curveball_pfx_z_std3/p_std3 as curveball_pfx_z_p_std3,
@curveball_mnorm_p := curveball_mnorm_std3/p_std3 as curveball_mnorm_p_std3,
@curveball_adjmnorm_p := curveball_adjmnorm_std3/p_std3 as curveball_adjmnorm_p_std3,

@slider_p := slider_std3/p_std3 as slider_p_std3,
@slider_endspeed_p := slider_endspeed_std3/p_std3 as slider_endspeed_p_std3,
@slider_spinrate_p := slider_spinrate_std3/p_std3 as slider_spinrate_p_std3,
@slider_spindir_p := slider_spindir_std3/p_std3 as slider_spindir_p_std3,
@slider_pfx_x_p := slider_pfx_x_std3/p_std3 as slider_pfx_x_p_std3,
@slider_pfx_z_p := slider_pfx_z_std3/p_std3 as slider_pfx_z_p_std3,
@slider_mnorm_p := slider_mnorm_std3/p_std3 as slider_mnorm_p_std3,
@slider_adjmnorm_p := slider_adjmnorm_std3/p_std3 as slider_adjmnorm_p_std3,

@changeup_p := changeup_std3/p_std3 as changeup_p_std3,
@changeup_endspeed_p := changeup_endspeed_std3/p_std3 as changeup_endspeed_p_std3,
@changeup_spinrate_p := changeup_spinrate_std3/p_std3 as changeup_spinrate_p_std3,
@changeup_spindir_p := changeup_spindir_std3/p_std3 as changeup_spindir_p_std3,
@changeup_pfx_x_p := changeup_pfx_x_std3/p_std3 as changeup_pfx_x_p_std3,
@changeup_pfx_z_p := changeup_pfx_z_std3/p_std3 as changeup_pfx_z_p_std3,
@changeup_mnorm_p := changeup_mnorm_std3/p_std3 as changeup_mnorm_p_std3,
@changeup_adjmnorm_p := changeup_adjmnorm_std3/p_std3 as changeup_adjmnorm_p_std3,

##### last60 ######

@outsmade_pa := outsmade_last60/pa_last60 as outsmade_pa_last60,
@hits_pa := hits_last60/pa_last60 as hits_pa_last60,
@avg_ := hits_last60/(pa_last60 - walks_last60 - hbp_last60) as avg_last60,
@obp := onbases_last60/pa_last60 as obp_last60,
@tba_pa := totbasesadv_last60/pa_last60 as tba_pa_last60,
@tba_o := totbasesadv_last60/outsmade_last60 as tba_o_last60,
@k_pa := k_last60/pa_last60 as k_pa_last60,
@klook_pa := klook_last60/pa_last60 as klook_pa_last60,
@kswing_pa := kswing_last60/pa_last60 as kswing_pa_last60,
@walk_pa := walks_last60/pa_last60 as walk_pa_last60,
@singles_pa := singles_last60/pa_last60 as singles_pa_last60,
@doubles_pa := doubles_last60/pa_last60 as doubles_pa_last60,
@triples_pa := triples_last60/pa_last60 as triples_pa_last60,
@homeruns_pa := homeruns_last60/pa_last60 as homeruns_pa_last60,
@groundballs_pa := groundballs_last60/pa_last60 as groundballs_pa_last60,
@linedrives_pa := linedrives_last60/pa_last60 as linedrives_pa_last60,

@ball_p := ball_last60/p_last60 as ball_p_last60,
@ball_pa := ball_last60/pa_last60 as ball_pa_last60,
@strike_p := strike_last60/p_last60 as strike_p_last60,
@strike_pa := strike_last60/pa_last60 as strike_pa_last60,

@calledstrike_strike := calledstrike_last60/strike_last60 as calledstrike_strike_last60,
@whiffstrike_strike := whiffstrike_last60/strike_last60 as whiffstrike_strike_last60,
@foulstrike_strike := foulstrike_last60/strike_last60 as foulstrike_strike_last60,
@inplay_strike := inplay_last60/strike_last60 as inplay_strike_last60,
@calledstrike_pa := calledstrike_last60/pa_last60 as calledstrike_pa_last60,
@whiffstrike_pa := whiffstrike_last60/pa_last60 as whiffstrike_pa_last60,
@foulstrike_pa := foulstrike_last60/pa_last60 as foulstrike_pa_last60,
@inplay_pa := inplay_last60/pa_last60 as inplay_pa_last60,

@swing_p := swing_last60/p_last60 as swing_p_last60,
@take_p := take_last60/p_last60 as take_p_last60,
@swing_pa := swing_last60/pa_last60 as swing_pa_last60,
@take_pa := take_last60/pa_last60 as take_pa_last60,

@firstpstrike_pa := firstpstrike_last60/pa_last60 as firstpstrike_pa_last60,
@secondpstrike_pa := secondpstrike_last60/firstpnotinplay_fl_last60 as secondpstrike_pa_last60,

@zoneedge_in2_p := zoneedge_in2_last60/p_last60 as zoneedge_in2_p_last60,
@zoneedge_in4_p := zoneedge_in4_last60/p_last60 as zoneedge_in4_p_last60,
@zoneedge_out2_p := zoneedge_out2_last60/p_last60 as zoneedge_out2_p_last60,
@zoneedge_out4_p := zoneedge_out4_last60/p_last60 as zoneedge_out4_p_last60,
@zonecorn_in2_p := zonecorn_in2_last60/p_last60 as zonecorn_in2_p_last60,
@zonecorn_in4_p := zonecorn_in4_last60/p_last60 as zonecorn_in4_p_last60,
@zonecorn_out2_p := zonecorn_out2_last60/p_last60 as zonecorn_out2_p_last60,
@zonecorn_out4_p := zonecorn_out4_last60/p_last60 as zonecorn_out4_p_last60,
@zone_mid3_p := zone_mid3_last60/p_last60 as zone_mid3_p_last60,
@zone_mid6_p := zone_mid6_last60/p_last60 as zone_mid6_p_last60,
@zone_bigmiss4_p := zone_bigmiss4_last60/p_last60 as zone_bigmiss4_p_last60,

@fastball_p := fastball_last60/p_last60 as fastball_p_last60,
@fastball_endspeed_p := fastball_endspeed_last60/p_last60 as fastball_endspeed_p_last60,
@fastball_spinrate_p := fastball_spinrate_last60/p_last60 as fastball_spinrate_p_last60,
@fastball_spindir_p := fastball_spindir_last60/p_last60 as fastball_spindir_p_last60,
@fastball_pfx_x_p := fastball_pfx_x_last60/p_last60 as fastball_pfx_x_p_last60,
@fastball_pfx_z_p := fastball_pfx_z_last60/p_last60 as fastball_pfx_z_p_last60,
@fastball_mnorm_p := fastball_mnorm_last60/p_last60 as fastball_mnorm_p_last60,
@fastball_adjmnorm_p := fastball_adjmnorm_last60/p_last60 as fastball_adjmnorm_p_last60,

@curveball_p := curveball_last60/p_last60 as curveball_p_last60,
@curveball_endspeed_p := curveball_endspeed_last60/p_last60 as curveball_endspeed_p_last60,
@curveball_spinrate_p := curveball_spinrate_last60/p_last60 as curveball_spinrate_p_last60,
@curveball_spindir_p := curveball_spindir_last60/p_last60 as curveball_spindir_p_last60,
@curveball_pfx_x_p := curveball_pfx_x_last60/p_last60 as curveball_pfx_x_p_last60,
@curveball_pfx_z_p := curveball_pfx_z_last60/p_last60 as curveball_pfx_z_p_last60,
@curveball_mnorm_p := curveball_mnorm_last60/p_last60 as curveball_mnorm_p_last60,
@curveball_adjmnorm_p := curveball_adjmnorm_last60/p_last60 as curveball_adjmnorm_p_last60,

@slider_p := slider_last60/p_last60 as slider_p_last60,
@slider_endspeed_p := slider_endspeed_last60/p_last60 as slider_endspeed_p_last60,
@slider_spinrate_p := slider_spinrate_last60/p_last60 as slider_spinrate_p_last60,
@slider_spindir_p := slider_spindir_last60/p_last60 as slider_spindir_p_last60,
@slider_pfx_x_p := slider_pfx_x_last60/p_last60 as slider_pfx_x_p_last60,
@slider_pfx_z_p := slider_pfx_z_last60/p_last60 as slider_pfx_z_p_last60,
@slider_mnorm_p := slider_mnorm_last60/p_last60 as slider_mnorm_p_last60,
@slider_adjmnorm_p := slider_adjmnorm_last60/p_last60 as slider_adjmnorm_p_last60,

@changeup_p := changeup_last60/p_last60 as changeup_p_last60,
@changeup_endspeed_p := changeup_endspeed_last60/p_last60 as changeup_endspeed_p_last60,
@changeup_spinrate_p := changeup_spinrate_last60/p_last60 as changeup_spinrate_p_last60,
@changeup_spindir_p := changeup_spindir_last60/p_last60 as changeup_spindir_p_last60,
@changeup_pfx_x_p := changeup_pfx_x_last60/p_last60 as changeup_pfx_x_p_last60,
@changeup_pfx_z_p := changeup_pfx_z_last60/p_last60 as changeup_pfx_z_p_last60,
@changeup_mnorm_p := changeup_mnorm_last60/p_last60 as changeup_mnorm_p_last60,
@changeup_adjmnorm_p := changeup_adjmnorm_last60/p_last60 as changeup_adjmnorm_p_last60,

##### last20 ######

@outsmade_pa := outsmade_last20/pa_last20 as outsmade_pa_last20,
@hits_pa := hits_last20/pa_last20 as hits_pa_last20,
@avg_ := hits_last20/(pa_last20 - walks_last20 - hbp_last20) as avg_last20,
@obp := onbases_last20/pa_last20 as obp_last20,
@tba_pa := totbasesadv_last20/pa_last20 as tba_pa_last20,
@tba_o := totbasesadv_last20/outsmade_last20 as tba_o_last20,
@k_pa := k_last20/pa_last20 as k_pa_last20,
@klook_pa := klook_last20/pa_last20 as klook_pa_last20,
@kswing_pa := kswing_last20/pa_last20 as kswing_pa_last20,
@walk_pa := walks_last20/pa_last20 as walk_pa_last20,
@singles_pa := singles_last20/pa_last20 as singles_pa_last20,
@doubles_pa := doubles_last20/pa_last20 as doubles_pa_last20,
@triples_pa := triples_last20/pa_last20 as triples_pa_last20,
@homeruns_pa := homeruns_last20/pa_last20 as homeruns_pa_last20,
@groundballs_pa := groundballs_last20/pa_last20 as groundballs_pa_last20,
@linedrives_pa := linedrives_last20/pa_last20 as linedrives_pa_last20,

@ball_p := ball_last20/p_last20 as ball_p_last20,
@ball_pa := ball_last20/pa_last20 as ball_pa_last20,
@strike_p := strike_last20/p_last20 as strike_p_last20,
@strike_pa := strike_last20/pa_last20 as strike_pa_last20,

@calledstrike_strike := calledstrike_last20/strike_last20 as calledstrike_strike_last20,
@whiffstrike_strike := whiffstrike_last20/strike_last20 as whiffstrike_strike_last20,
@foulstrike_strike := foulstrike_last20/strike_last20 as foulstrike_strike_last20,
@inplay_strike := inplay_last20/strike_last20 as inplay_strike_last20,
@calledstrike_pa := calledstrike_last20/pa_last20 as calledstrike_pa_last20,
@whiffstrike_pa := whiffstrike_last20/pa_last20 as whiffstrike_pa_last20,
@foulstrike_pa := foulstrike_last20/pa_last20 as foulstrike_pa_last20,
@inplay_pa := inplay_last20/pa_last20 as inplay_pa_last20,

@swing_p := swing_last20/p_last20 as swing_p_last20,
@take_p := take_last20/p_last20 as take_p_last20,
@swing_pa := swing_last20/pa_last20 as swing_pa_last20,
@take_pa := take_last20/pa_last20 as take_pa_last20,

@firstpstrike_pa := firstpstrike_last20/pa_last20 as firstpstrike_pa_last20,
@secondpstrike_pa := secondpstrike_last20/firstpnotinplay_fl_last20 as secondpstrike_pa_last20,

@zoneedge_in2_p := zoneedge_in2_last20/p_last20 as zoneedge_in2_p_last20,
@zoneedge_in4_p := zoneedge_in4_last20/p_last20 as zoneedge_in4_p_last20,
@zoneedge_out2_p := zoneedge_out2_last20/p_last20 as zoneedge_out2_p_last20,
@zoneedge_out4_p := zoneedge_out4_last20/p_last20 as zoneedge_out4_p_last20,
@zonecorn_in2_p := zonecorn_in2_last20/p_last20 as zonecorn_in2_p_last20,
@zonecorn_in4_p := zonecorn_in4_last20/p_last20 as zonecorn_in4_p_last20,
@zonecorn_out2_p := zonecorn_out2_last20/p_last20 as zonecorn_out2_p_last20,
@zonecorn_out4_p := zonecorn_out4_last20/p_last20 as zonecorn_out4_p_last20,
@zone_mid3_p := zone_mid3_last20/p_last20 as zone_mid3_p_last20,
@zone_mid6_p := zone_mid6_last20/p_last20 as zone_mid6_p_last20,
@zone_bigmiss4_p := zone_bigmiss4_last20/p_last20 as zone_bigmiss4_p_last20,

@fastball_p := fastball_last20/p_last20 as fastball_p_last20,
@fastball_endspeed_p := fastball_endspeed_last20/p_last20 as fastball_endspeed_p_last20,
@fastball_spinrate_p := fastball_spinrate_last20/p_last20 as fastball_spinrate_p_last20,
@fastball_spindir_p := fastball_spindir_last20/p_last20 as fastball_spindir_p_last20,
@fastball_pfx_x_p := fastball_pfx_x_last20/p_last20 as fastball_pfx_x_p_last20,
@fastball_pfx_z_p := fastball_pfx_z_last20/p_last20 as fastball_pfx_z_p_last20,
@fastball_mnorm_p := fastball_mnorm_last20/p_last20 as fastball_mnorm_p_last20,
@fastball_adjmnorm_p := fastball_adjmnorm_last20/p_last20 as fastball_adjmnorm_p_last20,

@curveball_p := curveball_last20/p_last20 as curveball_p_last20,
@curveball_endspeed_p := curveball_endspeed_last20/p_last20 as curveball_endspeed_p_last20,
@curveball_spinrate_p := curveball_spinrate_last20/p_last20 as curveball_spinrate_p_last20,
@curveball_spindir_p := curveball_spindir_last20/p_last20 as curveball_spindir_p_last20,
@curveball_pfx_x_p := curveball_pfx_x_last20/p_last20 as curveball_pfx_x_p_last20,
@curveball_pfx_z_p := curveball_pfx_z_last20/p_last20 as curveball_pfx_z_p_last20,
@curveball_mnorm_p := curveball_mnorm_last20/p_last20 as curveball_mnorm_p_last20,
@curveball_adjmnorm_p := curveball_adjmnorm_last20/p_last20 as curveball_adjmnorm_p_last20,

@slider_p := slider_last20/p_last20 as slider_p_last20,
@slider_endspeed_p := slider_endspeed_last20/p_last20 as slider_endspeed_p_last20,
@slider_spinrate_p := slider_spinrate_last20/p_last20 as slider_spinrate_p_last20,
@slider_spindir_p := slider_spindir_last20/p_last20 as slider_spindir_p_last20,
@slider_pfx_x_p := slider_pfx_x_last20/p_last20 as slider_pfx_x_p_last20,
@slider_pfx_z_p := slider_pfx_z_last20/p_last20 as slider_pfx_z_p_last20,
@slider_mnorm_p := slider_mnorm_last20/p_last20 as slider_mnorm_p_last20,
@slider_adjmnorm_p := slider_adjmnorm_last20/p_last20 as slider_adjmnorm_p_last20,

@changeup_p := changeup_last20/p_last20 as changeup_p_last20,
@changeup_endspeed_p := changeup_endspeed_last20/p_last20 as changeup_endspeed_p_last20,
@changeup_spinrate_p := changeup_spinrate_last20/p_last20 as changeup_spinrate_p_last20,
@changeup_spindir_p := changeup_spindir_last20/p_last20 as changeup_spindir_p_last20,
@changeup_pfx_x_p := changeup_pfx_x_last20/p_last20 as changeup_pfx_x_p_last20,
@changeup_pfx_z_p := changeup_pfx_z_last20/p_last20 as changeup_pfx_z_p_last20,
@changeup_mnorm_p := changeup_mnorm_last20/p_last20 as changeup_mnorm_p_last20,
@changeup_adjmnorm_p := changeup_adjmnorm_last20/p_last20 as changeup_adjmnorm_p_last20,

NULL as createddate,
NULL as lastmodifieddate,
NULL as autoincrement_PK

FROM anal_pitcher_counting_p as p
JOIN anal_pitcher_counting_ab as ab
ON p.anal_game_date = ab.anal_game_date
AND p.pitcher = ab.pitcher

ORDER BY anal_game_date DESC, curveball_adjmnorm_p_std DESC
;


#ALTER TABLE anal_pitcher_rate ADD UNIQUE KEY (anal_game_date,pitcher);
#ALTER TABLE anal_pitcher_rate ADD INDEX (pitcher);

#ALTER TABLE anal_pitcher_rate ADD COLUMN createddate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
#ALTER TABLE anal_pitcher_rate ADD COLUMN lastmodifiedddate timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP;
#ALTER TABLE anal_pitcher_rate ADD COLUMN anal_pitcher_counting_def_PK int auto_increment primary key;


